module ConstHelper
  STATUS_ERROR = -1
  STATUS_DELETED = 0
  STATUS_NOT_PROCESSED = 1
  STATUS_IN_PROCESS = 2
  STATUS_PROCESSED = 11
  STATUS_VISIBLE_FOR_BOT = 101
  ##
  BOT_STYLE_IMAGE = 101
  BOT_CONTENT_IMAGE = 101


end